---
- name: Install rpm
  yum:
    name: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    state: present

- name: Download mysql
  yum:
    name: mysql-community-server.x86_64
    state: latest

- name: Auto-start mysql
  service:
    name=mysqld
    enabled=yes

- name: Start mysql
  service:
    name=mysqld
    state=started

- name: Cut temp_passwd for ignore msg
  shell: grep 'temporary password' /var/log/mysqld.log | cut -d ':' -f 4-5
  register: temp_passwd

- name: Display temp_passwd
  debug:
    msg: "Please connect to {{ ansible_host }} for configure mysql with this temp passwd:{{ temp_passwd.stdout }}"
