---
- name: Download jdk8 in /busapps/dcvt/1.0/
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
    dest: /busapps/dcvt/1.0/
    headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    validate_certs: no

- name: Unarchive jdk8 in /busapps/dcvt/1.0
  unarchive: 
    src: /busapps/dcvt/1.0/jdk-8u161-linux-x64.tar.gz
    dest: /busapps/dcvt/1.0/
    remote_src: yes
    owner: DCVTGBLA
    group: DCVTGBLA