---
- name: Download and unarchive tomcat in /busapps/dctv/1.0/ with owner = DCVTGBLA
  unarchive:
    src: http://apache.mediamirrors.org/tomcat/tomcat-8/v8.5.28/bin/apache-tomcat-8.5.28.tar.gz
    dest: /busapps/dcvt/1.0/
    remote_src: yes
    owner: DCVTGBLA
    group: DCVTGBLA

- name: RM logs folder in /busapps/dctv/1.0/apache-tomcat-8.5.28
  file:
    path: /busapps/dctv/1.0/apache-tomcat-8.5.28/logs
    state: absent

- name: Copy tomcat.service to /etc/systemd/system
  copy:
    src: /etc/ansible/file_for_host/tomcat.service
    dest: /etc/systemd/system/tomcat.service

- name: Auto-start tomcat
  service:
    name=tomcat
    enabled=yes

- name: Start tomcat
  service:
    name=tomcat
    state=started

#- name: SL apache-tomcat-8.5.28/logs to /busdata/dcvt/1.0/logs/
#  file:
#    src: /busdata/dcvt/1.0/logs
#    dest: /busapps/dcvt/1.0/apache-tomcat-8.5.28/logs
#    state: link
#    owner: DCVTGBLA
#    group: DCVTGBLA